### ISSUE TITLE
Suggestion: Automatically set the correct model each map is supposed to use in the ControlNet setting when selecting "Send to txt2img/img2img"

### ISSUE THREAD

**Issue by Sisimshow** [ZhUyU1997/open-pose-editor#25]
For example, setting the OpenPose map to use the OpenPose model or the depth map of the hands to use the depth model in the settings automatically so it doesn't need to be set manually.

Just a QoL feature that saves a bit of time.

**Comment by nonnonstop** [comment]
Please report to https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/issues

Maybe because the feedback link is still here. Sorry.
I'll change it later.

**Comment by ZhUyU1997** [comment]
Assign to [sd-webui-3d-open-pose-editor/issues](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/issues)
