### ISSUE TITLE
Issue: Generate button doesn't seem to work

### ISSUE THREAD

**Issue by Sisimshow** [ZhUyU1997/open-pose-editor#26]
The original one that's layered over the canvas still works, but the new one added to the GUI on the right doesn't. It does nothing when clicked and there are no console errors. Not a big deal but figured it should be reported.
![Screenshot 2023-03-26 203853](https://user-images.githubusercontent.com/126213271/227815606-c53a1740-5ac7-418c-ae7e-a8527f36f2c3.png)

**Comment by nonnonstop** [comment]
Please report to https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/issues
