### ISSUE TITLE
reset fingers position and export png with black background

### ISSUE THREAD

**Issue by jmzg** [ZhUyU1997/open-pose-editor#3]
Could you add a function to reset the finger's original position?
Could you add an export function to png with the black background?

**Comment by ZhUyU1997** [comment]
Hello, I don't understand the png with the background. Could you explain more?
The first request will be supported in the next version.

**Comment by jmzg** [comment]
Thank you very much for your quick response.
PNG is a format of image, and it is similar to JPEG.

**Comment by thulle** [comment]
@jmzg I just click the Skeleton Map/Depth map/etc-button in the toolbar to update the 4 buttons in the lower right, clicking those then gives me a .png of skeleton/depth map/etc.. Isn't that how it already works for you?

**Comment by jmzg** [comment]
You are awesome! You are the best!!!
Thank you very much!!!

**Comment by CCpt5** [comment]
This thread was helpful for me too, btw. I didn't understand that you needed to click the "skeleton map/depth map/normal map/edge" button to populate/refresh the images in the bottom right. Instead I was clicking on the boxes and getting an option to download "download.html" and assumed my browser's script blocker was breaking that functionality. It may be worth considering rewording that button or directing users to it when clicking blank boxes w/ a message.

I agree this is an outstanding tool Thanks very much for developing it!! Best I've used so far, and I love the new "random pose" option!

**Comment by ZhUyU1997** [comment]
> This thread was helpful for me too, btw. I didn't understand that you needed to click the "skeleton map/depth map/normal map/edge" button to populate/refresh the images in the bottom right. Instead I was clicking on the boxes and getting an option to download "download.html" and assumed my browser's script blocker was breaking that functionality. It may be worth considering rewording that button or directing users to it when clicking blank boxes w/ a message.
> 
> I agree this is an outstanding tool Thanks very much for developing it!! Best I've used so far, and I love the new "random pose" option!

Thanks for your advice! I update the order and text. Hope it is useful.
