### ISSUE TITLE
input quá khó để nhập chính xác

### ISSUE THREAD

**Issue by nghiatruong2k1** [ZhUyU1997/open-pose-editor#36]
![image](https://user-images.githubusercontent.com/103102262/228708655-22966fc0-304b-46f6-b147-6939f44395ab.png)

**Comment by ZhUyU1997** [comment]
Ok，I will add a input to directly set value, Thanks for your feedback

**Comment by ZhUyU1997** [comment]
I supported it, Please feel free to open it if still meet this issue.
