### ISSUE TITLE
How to export 3D keypoints like openpose2d(18 keypoints)?

### ISSUE THREAD

**Issue by CiaoHe** [ZhUyU1997/open-pose-editor#38]
Thx your amazing work. Could you support exporting 3D keypoints like openpose2d(18 keypoints)?

**Comment by CiaoHe** [comment]
I want to export it for 3D keypoints controlled DreamFusion-like model, which will built on ControlNet-openpose SD model

**Comment by ZhUyU1997** [comment]
Ok, I will want to get details info in export format, Can you give more documents or link?

**Comment by CiaoHe** [comment]
Wow, thx a lot for your consideration!
1. The pose output format best be COCO version:
![](https://cmu-perceptual-computing-lab.github.io/openpose/web/html/.github/media/keypoints_pose_18.png)
where the 3d keypoints should be like an array in shape of [18,3]
```python
{"Nose", 0 }, { "Neck", 1 }, { "RShoulder", 2 }, { "RElbow", 3 }, {"RWrist",4},
{ "LShoulder",5 }, { "LElbow", 6 }, { "LWrist", 7 }, { "RHip", 8 }, {"RKnee",9},
{ "RAnkle", 10 }, { "LHip", 11 }, { "LKnee", 12 }, { "LAnkle", 13 }, {"Background",18}
{"REye",14}, { "LEye", 15 }, { "REar", 16 }, { "LEar", 17 },
```

2. the output 3d keypoints should be in `world-coordinate` (`camera-coordinate` is OK, but this requires additional `R` and `T`), and requires related camera intrinsic parameter (`K`: `fx`,`fy`,`cx`,`cy`)

**Comment by ZhUyU1997** [comment]
![image](https://user-images.githubusercontent.com/18410894/229308619-a71bc8b2-6759-4c11-bb18-26c10268623f.png)
I updated it. Please mouse right-click to get this function. 
Please feel free to open this issue.

**Comment by CiaoHe** [comment]
wow, great thanks!
