### ISSUE TITLE
Touching hip width parameter switches the hips & legs

### ISSUE THREAD

**Issue by thulle** [ZhUyU1997/open-pose-editor#4]
First, thanks for the great editor! 

Using the interface at https://zhuyu1997.github.io/open-pose-editor/ works fine, but touching the hip width parameter switches side of the hips/legs.
Before touching the controller, green hip to the left, blue hip to the right:
![before](https://user-images.githubusercontent.com/1105866/224714196-ab130bde-3156-43ed-9d77-7435a7a1e2eb.png)
After touching the controller, blue hip to the left, green hip to the right, and feet are mirrored:
![after](https://user-images.githubusercontent.com/1105866/224714243-e9b5abc5-f678-4a60-a480-1c64420c965b.png)

**Comment by ZhUyU1997** [comment]
Thanks, I fixed it, please check new version

**Comment by thulle** [comment]
Verified working on firefox (linux+android) and chromium. Thanks!
