### ISSUE TITLE
FPS drops when preview is enabled

### ISSUE THREAD

**Issue by nonnonstop** [ZhUyU1997/open-pose-editor#41]
Environment
===========
OS: Windows 10
Browser: Chrome 111.0.5563.147

Description
===========

With preview enabled, the FPS drops when the camera is rotated.
Especially when the camera is shot from above, the FPS drops to about 15 FPS.
![image](https://user-images.githubusercontent.com/42905588/229269363-0d0b96b9-ca5f-4f27-85cc-94b424caa17d.png)

Note: The source is changed to display Stats for reporting.

This problem occurs in commit 2ec3381baa5e01e59fb43c0d9ec3c46b56fd7555 and later.
This problem didn't occur in commit 42f18673d20b5610862a241c727135f889411c2f.

Steps to reproduce
==================
1. Open https://zhuyu1997.github.io/open-pose-editor/.
2. Left-click and drag to move the camera.
3. FPS drops and camera movement becomes a bit laggy.

Notes
=====

I don't know if it is related to this issue, but I found the following.

When the FPS is dropping, a large number of requests to the Data URL are occurring.
![image](https://user-images.githubusercontent.com/42905588/229270364-2959bfc2-2326-48a8-992a-2df92f8f597f.png)

Thank you for everything!

**Comment by ZhUyU1997** [comment]
Ok, I will try to optimize it.

**Comment by ZhUyU1997** [comment]
I fix it by resizing the image, but no idea about so many requests on dev tools. https://github.com/ZhUyU1997/open-pose-editor/commit/ccc8ef94a4d29b47a9b5f4d1aad1d3436ba68070
