### ISSUE TITLE
Feedback: Move + Rotation Gizmos are too big

### ISSUE THREAD

**Issue by strouder** [ZhUyU1997/open-pose-editor#46]
Please resize the gizmos to half size... or allow settings to control the size of the gizmos as they are too big. (Possible Hotkey - or +)

![Screenshot 2023-04-02 235550](https://user-images.githubusercontent.com/21327400/229364331-01ff9e1c-1cf4-44f5-87a0-02def2203dcf.png)

**Comment by ZhUyU1997** [comment]
Thanks for your feedback. I will improve it.
