### ISSUE TITLE
Feedback: Rotation Dots are too big when zoomed in.

### ISSUE THREAD

**Issue by strouder** [ZhUyU1997/open-pose-editor#47]
1. Red dots should remain the same size when the user zooms in or out. Right now, the red dots also get larger when the user zooms in. It's difficult to work on the fingers. 

![Screenshot 2023-04-02 235852](https://user-images.githubusercontent.com/21327400/229364580-26a03c6f-0f7c-4810-9673-3aa080240a3e.png)

2. When selecting a red dot of a specific finger, the rest of the red dots that are from the other fingers should be colored GRAY. it is very difficult to work on. 

![222222](https://user-images.githubusercontent.com/21327400/229364720-ef0abbf8-4195-49c8-8d3d-a18de18ce2e4.png)

3. When rotating the top joint of a finger, the rest of the fingers in the same group should also rotate... (https://www.youtube.com/watch?v=wBfSA1mDATY)

**Comment by ZhUyU1997** [comment]
Very good advice, I will list it in the plan.

**Comment by ZhUyU1997** [comment]
I improve the color. Other requests are not currently considered.
