### ISSUE TITLE
下载安装后在选项卡无法找到该选项

### ISSUE THREAD

**Issue by zhujet** [ZhUyU1997/open-pose-editor#48]

**Comment by ZhUyU1997** [comment]
你是使用 https://github.com/nonnonstop/sd-webui-3d-open-pose-editor 安装的吗?

**Comment by zhujet** [comment]
已经解决了，更新了下sd，有这个选项卡了

**Comment by shawhu** [comment]
为什么我在a1111里面找到的是 nonnonstop 的版本？应该下哪个？
