### ISSUE TITLE
add "Detect from image"

### ISSUE THREAD

**Issue by fumitakayano** [ZhUyU1997/open-pose-editor#5]
Thank you for making this Extension.
The camera and bone system give AI art a new sense of certainty.

Could you implement additional functions to make this function even easier to use?

"Detect from image" would be very useful to have a function to estimate the pose taken by the character in the loaded background image.

Since the functions are only pseudo-inferences, we think that the pose does not need to be accurate in the world space as long as it can infer the state seen from the current camera.

**Comment by ZhUyU1997** [comment]
I am sorry that not able to implement this feature. This project just runs on the browser, and doesn't have the power to detect poses

**Comment by ZhUyU1997** [comment]
@fumitakayano Already supported "Detect from image", enjoy it.
