### ISSUE TITLE
显示“正在下载 mediapipe 姿势模型”一直转圈。

### ISSUE THREAD

**Issue by xhoxye** [ZhUyU1997/open-pose-editor#52]
显示“正在下载 mediapipe 姿势模型”一直转圈。
不论是插件还是网页版都是，怎么才能下载？

**Comment by ZhUyU1997** [comment]
可以是试一下魔法

**Comment by ZhUyU1997** [comment]
只要开一次就行了，甚至断网也可以用，只要不清理浏览器缓存

**Comment by lic9425** [comment]
我使用快连vpn全局模式，以及v2rayN全局模式都无法下载模型，应该使用什么方式才能下载 MediaPipe 姿势模型呢？
