### ISSUE TITLE
Option for adjusting position of shoulder nodes back and forth.

### ISSUE THREAD

**Issue by DKnight54** [ZhUyU1997/open-pose-editor#6]
Hey, found this pose editor to be very functional and easy to use. However, I'd like to have a bit more flexibilty with regards to position of the shoulder nodes relative to the chest node. Currently, it's locked as a straight line, however, that means that the shoulders and chest are locked as a straight line. This makes it difficult to make fine adjustments as the shoulders relative to the center of the chest, and prevents making shrugs or hunch postures etc.

would appreciate if it's possible to look into adding some minor up/down, back/forward adjustment to the chest node to make this adjjustments possible.

**Comment by ZhUyU1997** [comment]
Already support redo-undo

**Comment by DKnight54** [comment]
Sorry, I did not mean the redo-undo, I meant the ability to adjust the shoulder nodes position independant of each other. Right now, shoulders are locked as a straight line, unless I am missing a control that allows me to adjust the shoulders individually.

As you can see from the screenshot provided, that prevents some of the more subtle shoulder positions.
![image](https://user-images.githubusercontent.com/126916963/226101184-c149dd93-b7e5-4b9c-971b-6cb553c941bb.png)
